### ISSUE TITLE
Gilbert's comments

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-security-intro#16]
- [x] Please update the server.xml and java files for the guidelines
  - Wrap lines at 88 characters to maintain readability in editors and on the website.
  - Use 4 spaces instead of tabs for indentation.
  - ![screen shot 2018-08-24 at 9 55 20 am](https://user-images.githubusercontent.com/29576299/44589844-a4140880-a787-11e8-874d-a9c8eb7cc44d.png)
- [x] The following link should be either https://localhost:9091 or http://localhost:9090 if it can be redirected to https
```
      Next, point your browser to:
      https://localhost:9080
```
- [x] Suggest to have a better look for the profile, e.g.
```
      User name: alice
      User has administrator role: false
      User has user role: true
```
- [x] Suggest to the index page as following
  - [Click here](url) to check your profile if you are an administrator or a user.
  - [Click here](url) to check the application information if you are an administrator. 
- [x] The user, password, role tables at the finish and start section should be same
  - including to add a group column as the team suggested in the demo meeting
- [x] typo
  -  the back end services ->  the backend services
- [x] ProfileServlet.java
   - change `response.getWriter().write("Username: " + contextName + "\n");` to `pw.write("User name: " + contextName + "\n");`
- [x] ApplicationBean.java
  - better add `private static final long serialVersionUID = 1L;`
- [x] I guess the UISerive app is a war and not directly reference to the classes directory (or because of one more directory level, frontendUI, involved). The following statement is not true anymore:
  - If you make changes to the code, use the Maven compile goal to rebuild the application and have the running Open Liberty server pick them up automatically:
- [ ] Is following normal?
  - cd finish directory
  - run `mvn install`
    - a target directory was created at finish/backendServices and finish/frontendUI
    - no target directory was created at finish/
  - run `mvn liberty:start-server`
    - a target directory was created at finish/
```
      finish\
        |- backendServices
        |    |- target
        |- frontendUI
        |    |- target
        |- target
```
**YES**

**Comment by gkwan-ibm** [comment]
What is the finish\target for ? Test?

**Comment by JunyiSun** [comment]
It's there because of the plugin ```
  <plugin>
                    <groupId>net.wasdev.wlp.maven.plugins</groupId>
                    <artifactId>liberty-maven-plugin</artifactId>
                    <version>2.4</version>
                    <configuration>
                        <assemblyArtifact>
                            <groupId>io.openliberty</groupId>
                            <artifactId>openliberty-runtime</artifactId>
                            <version>${version.liberty}</version>
                            <type>zip</type>
                        </assemblyArtifact>
                    </configuration>
                </plugin>``` in the parent pom file

We have this plugin in the parent because we want to execute `mvn liberty:start-server` command directly in the `finish` folder to start both servers(frontend+backend) so we don't need to run `mvn liberty:start-server` two times in the two child folders respectively.
