### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-security-intro#19]
If we can elaborate on the below, it will make the guide even better IMHO:

- [x] What is authentication and what is authorization?  What's the difference?  We mentioned them but didn't explain until later.  Perhaps this is a matter of revising the "What you'll learn" section and making things cleaner, crisper, and clearer.
  - Why security?
 - [x] Why do we need to worry about or use a registry?  What is it for (besides explaining what it is)?
 - [x]  Why basic registry?
- [x] Why should we encrypt the passwords?
- [x] Why form authentication?  Why not basic or rather, why form over basic?
- [x] What are ProfileServlet and ApplicationServlet?  What are they for?  We should explain them conceptually to make it easier for users to grasp their significance and what are we doing.

**Comment by gkwan-ibm** [comment]
Close this issue because the app and the readme were rewritten
