### ISSUE TITLE
Next step 

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/draft-guide-security-intro#21]
1. Technical review and ID review

2.  Wait until OL 18003 gets released in Sept, so that we can use the new `TransportGuarantee.CONFIDENTIAL` feature, we need to update the link with the https url (I made comments besides the parts where code/test/guide need to be changed later)

3. Feature versioning in the pom files. That's a new update going on recently for all the guides. 
example: 
```
<dependency>
   <groupId>io.openliberty.features</groupId>
   <artifactId>jaxrs-2.1</artifactId>
   <type>esa</type>
   <scope>provided</scope>
 </dependency>
```

**Comment by gkwan-ibm** [comment]
2 and 3 addressed. 1 will be done in different process.
