### ISSUE TITLE
Gilbert's comment #2

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-security-intro#22]
- [ ] at the "Try what you'll build" section, tell users the links will forward to https automatically
- [ ] at the other section, tell users what make the links can be forwarded to https automatically
    -` The transportGuarantee=ServletSecurity.TransportGuarantee.CONFIDENTIAL configuration indicates that all user data must be encrypted by the transport.`
- [ ] suggest the /application to have link to home before the logout and /profile has similar layout
- [ ] tests failed - got 302 instead of 200

**Comment by justineechen** [comment]
Potential lines to be added to README.adoc to explain `ServletSecurity.TransportGuarantee.CONFIDENTIAL `
> The transport guarantee defines the data protection requirements that must be satisfied by the transport. In this case, the transport guarantee is set to the CONFIDENTIAL configuration which specifies that all user data must be encrypted during transport.

**Comment by gkwan-ibm** [comment]
The app, readme, and tests were re-implemented
