### ISSUE TITLE
Repo size is huge

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-security-intro#24]
The current repo size is 18M. Need to clean things up.

**Comment by evelinec** [comment]
This is still a problem for this guide, and need to be fixed.

**Comment by gkwan-ibm** [comment]
do you know what is wrong? Anything can show which directory used lot of resources?

**Comment by evelinec** [comment]
It's possible that the "target" folder content gets pushed into the repo. Ref to 
https://github.com/OpenLiberty/guide-microprofile-fallback/issues/6, for potential fixes.

**Comment by gkwan-ibm** [comment]
- cd draft-guide-security-intro
- git rev-list --objects --all > ../objects.txt
- investigate ../objects.txt of which history files/directories are not necessary
- repeated following for *events-finish/*, *.metadata/*, *jwt/*, *.DS_Store*
  - git filter-branch -f --index-filter 'git rm -r --cached --ignore-unmatch events-finish/' -- --all
  - git gc --aggressive --prune=now
  - git push origin --force

**Comment by gkwan-ibm** [comment]
@evelinec would verify the size of the repo? If you are ok, would you close this issue?

**Comment by evelinec** [comment]
Fresh cloned, 648K. Closed.
