### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-security-intro#37]
### General

- [ ] Title seems vague, could it be improved?
- [ ] On login form, button currently says "go" maybe "login" would work better
- [x] No way to get back to login screen after logging in as david (even after re-starting server)

### What you'll learn

- [x] "The application that you will be working with is a simple application." Perhaps mentioning the application they are working with as opposed to just referring to it as "a simple application"

### Try what you'll build

- [x] "Next, point your browser to: http://localhost:9080" -> Add a period after URL
- [x] @LoginToContinue in @FormAuthenticationMechanismDefinition annotations should be in backticks
- [x] "Because the HomeServlet also specifies the loginPage and errorPage attributes of the annotation @LoginToContinue in @FormAuthenticationMechanismDefinition ..." Sentence could be structured better to flow nicer. Perhaps: "Since the `HomeServlet` also specifies the loginPage and errorPage attributes in the `@LoginToContinue` annotation, ... "
- [x] Identity Store table values aren't aligned/centred properly with corresponding title
- [x] "Notice that when you sign in as Bob or Carl, the browser redirects to the admin page and you can view their names as well as their role as admin." -> "Notice that when you sign in as Bob or Carl, the browser redirects you to the admin page where you can view their names and roles. " or something similar. 

### Configuring the Identity Store
- [x] "However, we will be using Basic User Registry provided by Liberty, as a simple example of an identity store for the purposes of this guide." and "On the Open Liberty server, you can use a Basic User Registry as an identity store, to define the users and groups information." Seems redundant. 

### Encrypting passwords using securityUtility
- [x] Should "identity store" be capitalized? It is in other places of the guide.
- [x] "The passwords assigned to the accounts in identity store is encoded" -> "The passwords assigned to the accounts in identity store **are** encoded"
- [x] Here, alice and carl use **the** XOR encoding -> Here, alice and carl use XOR encoding
- [x] "Setting this variable **,** overrides the default key that is generated" -> Setting this variable overrides the default key that is generated
- [x] The configuration file itself is saved outside of the configuration directory for the server, this ensures that the file containing your key is not included when running **the the** server dump or package command. -> typo

### Implementing authentication
- [x] In the HomeServlet, the annotation links loginPage to welcome.html and errorPage to error.html that are required for the form authentication mechanism. -> In the HomeServlet, the annotation links loginPage to welcome.html and errorPage to error.html **which is** required for the form authentication mechanism.

### Adding authorization 
- [x] Authorization determines whether a user has the role required to access **to** whichever secondary page the HomeServlet will redirect them to. -> Authorization determines whether a user has the role required to access whichever secondary page the HomeServlet will redirect them to.
- [x] The method `securityContext.isCallerInRole(Utils.ADMIN)` returns a boolean that indicates if the current authenticated account is an admin or not. -> `securityContext.isCallerInRole(Utils.ADMIN)` is not a method.
- [x] The method `securityContext.isCallerInRole(Utils.USER)` returns a boolean that indicates if the current authenticated account is an user or not. -> Same as above
- [x] Open the src/main/webapp/WEB-INF/web.xml file: -> file isn't being displayed on the site

### Building and running the application
- [x] Use one of the credentials from the **above** table Identity Store to log in. -> avoid using directional words

### Great work! You're done!
- [x] Next, you can try the related MicroProfile-JWT guide. -> Should link the actual guide here
- [ ] Next, you can try the related MicroProfile-JWT guide. It demonstrates technologies to secure backend services. -> Next, you can try the related MicroProfile-JWT guide which demonstrates technologies to secure backend services. (or something similar).

**Comment by justineechen** [comment]
We decided to keep the "go" as the login button but we added a sentence that clarifies that this is a login page. Also, the extra bit about the MP JWT we didn't add because at the bottom of the guide there are related guides with the descriptions of the guide and JWT is one of them for security. We added the link to direct users straight to MP JWT though!

https://github.com/OpenLiberty/draft-guide-security-intro/pull/40

If you're okay with these changes we can close this issue. @andrewdes

**Comment by andrewdes** [comment]
After looking over the guide (after the above changes), I have some additional suggestions:

# Configuring the identity store
- [ ] "However, we will be using the basic registry provided by Liberty, as a simple example of an identity store for the purposes of this guide."  -> avoid using "we". Try: "However, for the purpose of this guide, a basic registry provided by Liberty is used as a simple example of an identity store." or something similar.

- [ ] "To do this, create the src/main/liberty/config/server.xml file:" -> avoid using "this", can be ambiguous

- [ ] "On the Open Liberty server, you can use the basic registry as an identity store, to define the users and groups information." ->  On the Open Liberty server, you can use the basic registry as an identity store to define the users and groups information.

# Encrypting passwords using securityUtility

- [ ] Navigate to `target/liberty/wlp/bin directory` -> Navigate to **the** `target/liberty/wlp/bin` directory
- [ ] "Navigate to target/liberty/wlp/bin directory **,** and run the following:" -> Navigate to target/liberty/wlp/bin directory and run the following:  (no comma)
- [ ] "Here, all users use the XOR encoding for their passwords." -> Where? Is the "here" referring to the command above or the application? Also, "all users" but I only see Bob.

# Adding authentication and authorization 

- [ ] "define `@FormAuthenticationMechanismDefinition` annotation" -> define **the** `@FormAuthenticationMechanismDefinition` annotation 
- [ ] The Security specification also defines a common SecurityContext API -> In the next sentence SecurityContext is in `backticks`, should be consistent. 
- [ ] "Because the HomeServlet also specifies the loginPage and errorPage attributes of the annotation @LoginToContinue in @FormAuthenticationMechanismDefinition" -> **Since** the HomeServlet also specifies the loginPage and errorPage attributes of the @LoginToContinue **annotation** in @FormAuthenticationMechanismDefinition.

Also, should the annotations be in `backticks`?

# Testing the application

- [ ] Create a test class in the `src/test/java/it/io/openliberty/guides/security/SecurityTest.java` file like the following: -> Create the `SecurityTest` class in the `src/test/java/it/io/openliberty/guides/security/SecurityTest.java` file:
- [ ] "There are four test cases. " -> Could this sentence be expanded to be more meaningful?
- [ ] The `testAuthenticationFail()` case tests -> The `testAuthenticationFail()` method tests 
(likewise for other three methods)
