### ISSUE TITLE
Review on 9/27's draft

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-security-intro#38]
What you'll learn

- [x] There're 5 small paragraphs in this section, some of them can be combined. ie, the first two. Then the 3rd and 4th can be connected, with "In this guide, you'll learn.."

- [x] The application that you will be working with is a simple application. => If a simple app, don't need to mention it? Just directly describing how the app work?

Try what you'll build

- [x] This section is too much technical info.. The purpose of this section is for user to try the app and have a quick feeling of what they are expected to see, ie, the end result, ie, after redirect, login with a user or two to see something. The content can be moved to the "Building and running the application" section, where more detail explanation of how to build and run the app can be described, after user has gone through learning about securing the app. 

- [x] Do "Identity Store" need to be cap'ed?

- [x] The user name "david" can be "dave" to make sound more friendly and matching with the other user names. But it's optional. 

- [x] There's a "Insecure Connection" message when first visiting the `https://localhost:9443/home` URL, where user needs to take the action to "Add Exception...". Not sure this needs to be mentioned in the guide. It's just a bit surprising to see a white warning page when first visiting the URL. 

- [x] Besides the "PartTime" group, the other group has no implication or explanation in this section.

Configuring the Identity Store

- [x] Not sure "Basic User Registry" needs to be and backticked? It's a type of registry like, LDAP. 

- [x] Here "identity store" is not cap'ed. I think they don't need to be cap'ed, and make it consistent throughout the guide. 

- [x] To do this, add the following configurations into the src/main/liberty/config/server.xml file: => it's unclear which configuration exactly to be added as the code snippet has all of the content in this file, so user needs to figure out which section to add. Regardless, this is not the structure and style we would like to have. Follow the guideline to include the entire `servier.xml` file, and then talk about the line or section of configuration. 

Encrypting passwords using securityUtility

- [x] This section seems quite long, and draws away the attention of the guide.. Not sure the detail explanation of how the `securityUntility` command work is needed for this guide. User can look it up in the KC?

Implementing authentication

- [x] Notice the @FormAuthenticationMechanismDefinition annotation in the class. The @LoginToContinue annotation allows the application to add specific login functionality to the AuthenticationMechanism. => The first sentence is not a proper sentence. These two sentence can be reworded. 

- [x] In the HomeServlet, the annotation links loginPage to welcome.html and errorPage to error.html that are required for the form authentication mechanism. => doesn't make sense.. what annotation links the html pages?

- [x] Generally, the explanation of how does authentication is implemented in the `HomeServlet` class is not clear and doesn't seem enough. 

Adding authorization

- [x] Open the src/main/java/io/openliberty/guides/ui/HomeServlet.java file: => perhaps "Refer to the.." class, which was already included in the previous section is enough? Including the same file again is not necessary and seems confusing.  

- [x] The "transport guarantee" element may be better to be `transportGuarantee` with be backtick to make it stand out more. 

- [x] The method securityContext.isCallerInRole(Utils.ADMIN) returns a boolean that indicates if the current authenticated account is an admin or not. => Perhaps "The method securityContext.isCallerInRole(Utils.ADMIN) within the `doGet` function.." is clearer as of where to look for this method.

Building and running the application

- [x] Again, the detail building and running the app section from "Try what you'll build" should be added here. 

Testing the application 
- [x] The test class path "src/test/java/it/io/openliberty/guides/security" is not pre-created.

- [x] The private methods in the test class can be moved to another file, to make the test class shorter and cleaner? It looks like the test case class is very long, but the explanation is rather short. Explanation is fine, just though the test case can be cleaner too.

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/draft-guide-security-intro/pull/40

I merged the issues we hadn't addressed yet here! Are there any other issues you would like us to address? @evelinec

**Comment by evelinec** [comment]
Thanks. I'll verify the fixes and let you know if there're additional things. FYI, the staging site is refreshed successfully.

**Comment by evelinec** [comment]
- [ ] One additional thing to keep in mind for the "Try what you'll build" section is that, it can be optional to user, meaning, they should be able to skip that section and still finish all of the guide.

**Comment by evelinec** [comment]
The rest of the feedback are all good. Nice fixes. 👍

**Comment by justineechen** [comment]
The fixes are included in this PR that has been merged: 
https://github.com/OpenLiberty/draft-guide-security-intro/pull/44

**Comment by evelinec** [comment]
- [ ] Re the 2nd point above, if you still need to talk about things in the server.xml file, I think separating the original server.xml file into the identitystore.xml and the new server.xml files, is not necessary. Just some explanation would be helpful. 

- [ ] If you really want to go with the new solution, then the reference to the `server.xml` file in the "Encrypting passwords using securityUtility" section, needs to be updated, because the new `server.xml` file doesn't have user passwords.

**Comment by evelinec** [comment]
Others are good.
