### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-security-intro#4]
**General** 
- [x] Title shouldn't have a period at the end
- [x] Description shouldn't mention appSecurity-3.0
- [x] Description is basically a mirror of the title
- [x] Directory structure is wrong in test folder. Refer to Project Structure section: https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles 
- [x] Is there a reason for having 2 finish folders?
- [x] Directory name (draft-guide-security-intro/finish/src/main/java/io/openliberty/guides/hello/) could be changed from hello to something more meaningful/relevant
- [ ] Spacing is off in the `server.xml` file
- [ ] Spacing is off in the `AdminServlet.java` file (extra spaces added at end of doGet method)
- [ ] Spacing is off in the `web.xml` file

**What you'll learn**
- [x] "You will learn how to secure **your** web application" -> "You will learn how to secure **a** web application"
- [x] "The most common **type of** authentication is username and password"
- [x] web.xml file -> `web.xml` file

**Getting Started**
- [x] Is this hard coded? Can use `include::{common-includes}/gitclone.adoc[]`

**Try what you'll build**
- [x] "contains the finished events application" -> What event application?
- [x] "Feel free to give it a try" Is this necessary? 
- [ ] `mvn install liberty:start-server` and `mvn liberty:stop-server` are in quotes instead of code blocks
- [ ] "Next, point your browser to: 
`http://localhost:9080/ServletSample` 
-> Next, point your browser to the `http://localhost:9080/ServletSample` URL. 
- [ ] "You can try out the authentication of the application by clicking the first link... " perhaps sentence would work better as 2 separate sentences
- [ ] "In order to sign in as different users" -> "In order to sign in as **a** different **user**"
- [ ] `mvn install liberty:start-server` produces following warning:

>  [WARNING] CWWKM2179W: The application is not defined in the server configuration but the POM configuration indicates it should be installed in the apps folder. Application configuration is being added to the target server configuration dropins folder by the plug-in.

- [x] Build fails:

> 
> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running io.openliberty.guides.hello.it.SecurityTest
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.512 sec <<< FAILURE! - in io.openliberty.guides.hello.it.SecurityTest
> testSuite(io.openliberty.guides.hello.it.SecurityTest)  Time elapsed: 1.499 sec  <<< FAILURE!
> java.lang.AssertionError: expected:<200> but was:<404>
>         at org.junit.Assert.fail(Assert.java:88)
>         at org.junit.Assert.failNotEquals(Assert.java:834)
>         at org.junit.Assert.assertEquals(Assert.java:645)
>         at org.junit.Assert.assertEquals(Assert.java:631)
>         at io.openliberty.guides.hello.it.SecurityTest.testCorrectAdmin(SecurityTest.java:76)
>         at io.openliberty.guides.hello.it.SecurityTest.testSuite(SecurityTest.java:68)
> 
> 
> Results :
> 
> Failed tests:
>   SecurityTest.testSuite:68->testCorrectAdmin:76 expected:<200> but was:<404>
> 
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Configuring a user registry**
- [x] You never tell the user to navigate to the start directory to begin
- [x] "add the following `Basic Registry`" should Basic Registry be capitalized and in quotes? Also, is following needed here? Perhaps "add the basic registry to the server.xml file" 
- [x] "server.xml file " -> `src/main/liberty/config/server.xml` file
- [x] "Now you've" -> "Now you have"
- [x] app -> application
- [x] "As you can see" -> is this necessary? 
- [x] "encoded here with Liberty's serverUtility command" is "here" needed?  Also perhaps it would be beneficial to explain what the serverUtility command does/provide a little bit of information about it
- [ ] "Here, the application uses the xor encoding" Not sure if "Here," is really needed. Also, perhaps you should explain what xor encoding is. Users could have a different technical backgrounds and may not know what this is.
- [ ] "There are two other supported encodings are well: hash and aes that can be used." Typo. Also, is the "as well" really needed? Same with "that can be used." 
- [ ] What does aes stand for? 

**Implementing authentication**
- [x] "Next, authentication ... " seems kind of weird starting a section off with "Next"
- [x] "This application uses Basic Authentication." Maybe try combining this sentence with the sentence after it. 
- [ ] "Open the `server.xml file` located under `liberty/config/server.xml`." -> Open the `src/main/liberty/config/server.xml` file.
- [x] "Notice how basic authentications is configured in the server.xml ..." -> These sentences may work better after the code block.
- [x] server.xml -> `server.xml` 
- [ ] "The auth-method specifies" what/where is this? I don't see it. 
- [x] "and the realm name is declared" what is a realm name? 
- [ ] "Remove the login-config from the server.xml file" -> Where is the login-config? I don't see it. You should also put the server.xml here, instead of just instructing the user to remove something.
- [ ] "shows the message ... if accessed" -> **when** accessed
- [ ] "open the HelloServlet.java file located at `src/main/java/io/openliberty/guides/hello`" Is this needed? Perhaps: To configure Basic Authentication, add the `@BasicAuthenticationMechanismDefinition` to the `src/main/java/io/openliberty/guides/hello/HelloServlet.java file`"

**Implementing authorization**
- [ ] "This is currently configured in the web.xml file under webapp/WEB-INF." The word `this` can be ambiguous.
- [ ] "configured in the web.xml file under webpapp/WEB-INF" -> configured in the `src/main/webapp/WEB-INF/web.xml` file.
- [x] "This can be achieved .. " This is ambiguous, what can be achieved?
- [x] "Remove the security-constraints and open the HelloServlet.java and add the following ... "  remove the security-constraints from where? The `HelloServlet.java` or the `web.xml`?
- [x] "open the HelloServlet.java and add the following @ServletSecurity annotation to the class:" -> Add the `@ServletSecurity` annotation the the `HelloServlet` class in the `src/main/java/io/openliberty/guides/hello/HelloServlet.java` file: "
- [x] "Now, open the AdminServlet.java file and add the same annotation, except only allow "admin" in roles allowed." Use entire path to file. Also, what annotation? Perhaps easier to just show annotation instead of telling user to add the same annotation. 
- [x] "This specifies that even if.. " what is "this" referring to? 

**Starting the application**
- [x] What is this section? Shouldn't this information be in the `Building the application` section?

**Testing the application**
- [ ] "Create the test class, src/test/java/io/openliberty/guides/hello/it/SecurityTest.java." -> Create the `src/test/java/io/openliberty/guides/hello/it/SecurityTest.java` test class
- [ ] Add to explanation of what the tests are doing

**Comment by JunyiSun** [comment]
Close this issue since it applies to Justine's version
