### ISSUE TITLE
Quick review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-security-intro#49]
_It also provides a SecurityContext API for programmatic security checks in Java EE containers._
In Java EE containers?  Should be application or your code.  The API allows you to access security information.

_Java EE Security provides capability to configure the basic, form or custom form authentication mechanism by using annotations in the servlets. It also provides a SecurityContext API for programmatic security checks in Java EE containers. You’ll learn how to implement form authentication. Form authentication allows you to specify the web application login and error pages, assign the security constraint of a servlet and use the SecurityContext API to determine the role of a logged in user._
We can break the above into paragraphs for easier read.

_The identity store is provided with the following user information credentials:_
The identify store provided is defined with the following user crendentials

_Now you can sign in to the HomeServlet with one of the credentials from the identity store._
HomeServlet?  I would say the application.

Why do we do an inclusion for the server.xml?  If we want to do so, we should explain why and the benefits?

_Within the <application-bnd> tags, two different authorization roles are assigned to these groups: admin and user._
Tags?  Should we say elements?

_Encrypting passwords using securityUtility_
Make a note that it is not recommended to store passwords in plain text?

_Open the src/main/webapp/WEB-INF/web.xml file:_
Do we need the user to edit this?  If not, it should not be copyable?

_// Return if expect the login should fail_
More like "Return if the login fail"?

_Next, you can try the related MicroProfile-JWT guide._
Shouldn't have a dash between MicroProfile and JWT?

**Comment by yeekangc** [comment]
@justineechen @gkwan-ibm, do we need the index.html?  Can the servlet handle directly?

Also, for the below:

_Welcome to this Sample Application
This application is secured, please login to continue._

Consider something like the below.  We can check with ID too.

Sample Application
This is a secure application. Login to continue.

**Comment by gkwan-ibm** [comment]
Yes the index.html is needed. If directly use servlet  for the welcome page, the web container does not challenge the authorization of the servlet and directly execute it. The role cannot be determined in the servlet.

**Comment by justineechen** [comment]
I addressed these points in this PR: https://github.com/OpenLiberty/draft-guide-security-intro/pull/50
and the guide is going through SME review now!

**Comment by yeekangc** [comment]
Addressed in #60.
