### ISSUE TITLE
User Guide Review

### ISSUE THREAD

**Issue by Rachelwrq** [OpenLiberty/draft-guide-security-intro#56]
### General Feedback
The guide is very informative and showed no logical errors. The flow was relatively smooth, there are a few suggestions:
- [ ] Might be irrelevant but brief information about the other type of authentication would be helpful for audience to distinguish between basic, form, and custom form.
- [x] Adjust the flow to give a more specific definition for from authentication near the beginning of the guide, because right now the actual definition is under the section `Adding authentication and authorization` which is presented in the middle of the guide.

#### Getting started
- [ ] Maybe mention that some user need to refresh the site manually after hitting the url: `http://localhost:9080`.
- [x] For the table, it is a little bit weird to look at the blank space for 'dave` and his `Role`. Even though it is later explained in the text, maybe just put no roles or N/A?

#### Configuring the user registry
- [x] There shouldn't be a space between user and name in the second paragraph, second line.
- [x] Since the user don't have a target folder at this point as `mvn install` is yet to be called, the command `./securityUtility encode --encoding=xor bobpwd` cannot be called in the start folder.

#### Adding authentication and authorization
- [x] In the first paragraph under the code snippet, `loginToContinue` attribute needs markup.

**Comment by justineechen** [comment]
The other issues are addressed in: https://github.com/OpenLiberty/draft-guide-security-intro/pull/55
and https://github.com/OpenLiberty/draft-guide-security-intro/pull/58
