### ISSUE TITLE
ID Review 

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-security-intro#65]
- [ ]  In "what you'll learn" section: 
_Java EE Security provides capability to configure the basic, form or custom form authentication mechanism -- Remove the comma between basic and form._

- [x] In the "Getting started" section:
"The application automatically switches from a HTTP connection to a..."
_Change "a HTTP connection" to "an HTTP connection"_

- [x] In the "Getting started" section:
"Now, sign into the application with one of the following user credentials from the user registry, which has been provided to you"
_Recommend removing "Now," so that the sentence begins with "Sign into the application"
Also, a question here: Have the credentials been provided? Or the registry? I assume its both, the registry, which contains the credentials. If we're trying to say that the registry has been provided, it looks good. If we're referring to the credentials, we might want to change the sentence to read "...which have been provided to you."_

- [x] In "Adding authentication and authorization":
"which is why a HTTP"
_Change "a HTTP" to "an HTTP"_

- [x] In the "Building and running the application" section:
"Point your browser to http://localhost:9080. As you can see, the browser gets redirected from a HTTP connection to a HTTPS connection automatically,..."

- [x] Change "from a HTTP connection to a HTTPS connection" to "from an HTTP connection to an HTTPS connection automatically..."

- [ ] Also, It looks like the building and running section is duplicated in the "try what you'll build" section. The table and the next few paragraphs appear twice in the guide and appear to have the same information. Was this intentional? Should it be removed from one section?

- [x] If I missed any instances of "a/an HTTP", I'd recommend running a search and replace on the file for "a HTTP" and replacing it with "an".

**Comment by justineechen** [comment]
- Basic authentication is one of three types of authentication types

**Comment by yeekangc** [comment]
"Java EE Security provides capability to configure the basic, form or custom form authentication mechanism -- Remove the comma between basic and form." -- The comma should not be removed.

If we want to fix, we can consider "Java EE Security provides capability to configure the basic authentication, form authentication or custom form authentication mechanism".

**Comment by justineechen** [comment]
This isn't the first time someone mentioned this point so I think I should implement the fix you suggested.

**Comment by justineechen** [comment]
The changes are implemented here: https://github.com/OpenLiberty/draft-guide-security-intro/pull/66

**Comment by rhpeters** [comment]
@justineechen and @yeekangc, thanks for the clarification on the forms of authorization. The way it read, it seemed like there were only two forms available. The suggestion YK made for how to fix it sounds great.

**Comment by rhpeters** [comment]
ID reviewed. Thank you @justineechen!
